### ISSUE TITLE
It not work on python 3.12 :(

### ISSUE THREAD

**Issue by anwikipedia** [fcangialosi/naver_tts#1]
I install pip3 install requests. But it still show error  : 
= RESTART: C:\Users\ADMIN\Desktop\naver_tts-master\naver.py
Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\naver_tts-master\naver.py", line 29, in <module>
    text = unicode(sys.argv[1], 'utf-8')
NameError: name 'unicode' is not defined. Did you mean: 'encode'?

When i try replace unicode with encode it show another error : 

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\naver_tts-master\naver.py", line 29, in <module>
    text = encode(sys.argv[1], 'utf-8')
IndexError: list index out of range

Please someone good at python help community korean learn language.

**Comment by fcangialosi** [comment]
hi @anwikipedia, I just pushed a commit that fixes this issue directly. unfortunately, it seems naver/papago changed their API, so the script will no longer work, regardless of python version, without a fix for this.

unfortunately i don't have time to work on this right now, but it should be fairly straight forward if someone sees this and wants to fix it in the future:

originally the naver makeID API was stateless, but now it requires a session cookie. so you'd have to do the following:
1. issue a request to get a cookie
2. supply that cookie to the makeID POST call

hope this helps, and sorry i'm unable to fix it fully at the moment!

**Comment by anwikipedia** [comment]
Thanks for trying!
